# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='owner',
        ),
    ]
