# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170815_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
