# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20170821_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.NullBooleanField(default=False),
        ),
    ]
