# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170824_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
