# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20170824_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='priority',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='sub_name',
            field=models.TextField(),
        ),
    ]
